### ISSUE TITLE
handle secrets from google secrets manager

### ISSUE THREAD

**Issue by rawlingsj** [chainguard-dev/terraform-google-cron#6]
For applications that run Google Cloud Run it would be good to pass a Terraform var for a secret key and name that points to a real secret in GSM.

Two options:
1. add something similar to https://github.com/chainguard-dev/terraform-google-cron/blob/94b43c715a17b9365778fc49e23b7b42ab2e58be/main.tf#L33-L38

but instead do the equivalent of:
```
      containers:
      - image: IMAGE_URL
        env:
        - name: ENV_VAR
          valueFrom:
            secretKeyRef:
              key: VERSION
              name: SECRET_NAME
```
2.  Envars aren't really that great, although it makes it easy for applications to use them. An alternative is we mount the secret as a volume for the application to read.

the equivalent of:

```
      containers:
      - image: IMAGE_URL
        volumeMounts:
        - mountPath: MOUNT_PATH
          name: VOLUME_NAME
      volumes:
      - name: VOLUME_NAME
        secret:
          items:
          - key: VERSION
            path: FILENAME
          secretName: SECRET_NAME
```
